### ISSUE TITLE
Invalid numeric value problem

### ISSUE THREAD

**Issue by kerimovscreations** [SaeidBsn/GDCheckbox#1]
Hi, thank you for such a library. I faced such a problem while adding dynamic checkboxes inside collection view cells. Can you update library with fixing this problem?
[Unknown process name] Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.
 [Unknown process name] Backtrace:
  <CGFloatValidateWithLog+57>
   <CGPathAddLineToPoint+82>
    <-[UIBezierPath addLineToPoint:]+27>
     <_T012lunchify_ios10GDCheckboxC9checkPath33_1F02B49C182E85D24E82DDAF7B5316CBLLSo08UIBezierE0Cfg+1998>
      <_T012lunchify_ios10GDCheckboxC10drawLayers33_1F02B49C182E85D24E82DDAF7B5316CBLLyyF+716>
       <_T012lunchify_ios10GDCheckboxC18initializeCheckbox33_1F02B49C182E85D24E82DDAF7B5316CBLLyyF+174>
        <_T012lunchify_ios10GDCheckboxCACSC6CGRectV5frame_tcfc+1470>
         <_T012lunchify_ios10GDCheckboxCACSC6CGRectV5frame_tcfcTo+38>
          <-[UIView init]+62>
           <_T0So9UIControlCABycfcTO+19>
            <_T0So9UIControlCABycfC+60>

**Comment by saeid** [comment]
Hi @kerimovscreations can you give me more details about the issue you're having? and what version of Xcode you are using?

**Comment by kerimovscreations** [comment]
Hi @saeid , I'm using Xcode 9.0 and trying to add checkbox inside the table view cell programmatically:
`func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell{
        if let cell = tableView.dequeueReusableCell(withIdentifier: "popup_filter_category_cell", for: indexPath) as? PopupFilterCategoryTableViewCell {
            
            cell.name.text = filters[indexPath.row].name
            
            let checkbox: GDCheckbox = GDCheckbox()
            checkbox.frame = CGRect(x: 5, y: 5, width: 30, height: 30)
            
            checkbox.checkWidth = 2.0
            checkbox.containerWidth = 1.0
            checkbox.isCircular = true
            checkbox.isOn = self.resultCodes.contains(filters[indexPath.row].code)
            checkbox.isRadiobox = false
            checkbox.isSquare = false
            checkbox.shouldAnimate = false
            checkbox.shouldFillContainer = false
            checkbox.tag = indexPath.row + 1
            
            cell.checkboxView.addSubview(checkbox)
            
            return cell
        }else{
            return tableView.dequeueReusableCell(withIdentifier: "popup_filter_category_cell", for: indexPath)
        }
    }`
While running the project, I got such errors on log panel:
`2017-10-04 21:46:46.405700+0400 lunchify-ios[88269:22345421] [Unknown process name] Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.
2017-10-04 21:46:46.405782+0400 lunchify-ios[88269:22345421] [Unknown process name] If you want to see the backtrace, please set CG_NUMERICS_SHOW_BACKTRACE environmental variable.`
I added `CG_NUMERICS_SHOW_BACKTRACE` as an environmental variable and get this backtrace:
`[Unknown process name] Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.
[Unknown process name] Backtrace:
<CGFloatValidateWithLog+57>
<CGPathAddLineToPoint+82>
<-[UIBezierPath addLineToPoint:]+27>
<_T012lunchify_ios10GDCheckboxC9checkPath33_1F02B49C182E85D24E82DDAF7B5316CBLLSo08UIBezierE0Cfg+1998>
<_T012lunchify_ios10GDCheckboxC10drawLayers33_1F02B49C182E85D24E82DDAF7B5316CBLLyyF+716>
<_T012lunchify_ios10GDCheckboxC18initializeCheckbox33_1F02B49C182E85D24E82DDAF7B5316CBLLyyF+174>
<_T012lunchify_ios10GDCheckboxCACSC6CGRectV5frame_tcfc+1470>
<_T012lunchify_ios10GDCheckboxCACSC6CGRectV5frame_tcfcTo+38>
<-[UIView init]+62>
<_T0So9UIControlCABycfcTO+19>
<_T0So9UIControlCABycfC+60>`
Note: I'm displaying the tableview as a popup dialog using Presentr library.

**Comment by saeid** [comment]
OK thanks for the details👍🏻
Ill look into it.

**Comment by saeid** [comment]
@kerimovscreations I tried the situation you explained, and also tried `Presentr library` as you mentioned. the issue seems to be related to this library. I had the same issue when trying to present vc with this lib, but when i present the vc like 
`self.present(vc, animated: true, completion: nil)` worked just fine.
also tried to show view/vc as popup manually also worked fine.
please try to do your scenario of presenting your view/vc without this lib and let me know if the issue exists.
